//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webyneter.ComponentsAnalysis.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectFilesDir {
            get {
                return ((string)(this["ProjectFilesDir"]));
            }
            set {
                this["ProjectFilesDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte RecentProjectsMemorised {
            get {
                return ((byte)(this["RecentProjectsMemorised"]));
            }
            set {
                this["RecentProjectsMemorised"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InputFilesDir {
            get {
                return ((string)(this["InputFilesDir"]));
            }
            set {
                this["InputFilesDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFilesDir {
            get {
                return ((string)(this["OutputFilesDir"]));
            }
            set {
                this["OutputFilesDir"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte RecentProjectsMemorisedDefault {
            get {
                return ((byte)(this["RecentProjectsMemorisedDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 480")]
        public global::System.Drawing.Size AppWindowMinimumSizeDefault {
            get {
                return ((global::System.Drawing.Size)(this["AppWindowMinimumSizeDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru")]
        public global::System.Globalization.CultureInfo AppCurrentCulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["AppCurrentCulture"]));
            }
            set {
                this["AppCurrentCulture"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Projects")]
        public string ProjectFilesDirNameDefault {
            get {
                return ((string)(this["ProjectFilesDirNameDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Input")]
        public string InputFilesDirNameDefault {
            get {
                return ((string)(this["InputFilesDirNameDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Output")]
        public string OutputFilesDirNameDefault {
            get {
                return ((string)(this["OutputFilesDirNameDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::Accord.Statistics.Analysis.AnalysisMethod PCAMethod {
            get {
                return ((global::Accord.Statistics.Analysis.AnalysisMethod)(this["PCAMethod"]));
            }
            set {
                this["PCAMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KPCACenterInFeatureSpace {
            get {
                return ((bool)(this["KPCACenterInFeatureSpace"]));
            }
            set {
                this["KPCACenterInFeatureSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gaussian")]
        public global::Webyneter.ComponentsAnalysis.Core.Analysis.KPCA.KPCAKernelKind KPCAKernelKind {
            get {
                return ((global::Webyneter.ComponentsAnalysis.Core.Analysis.KPCA.KPCAKernelKind)(this["KPCAKernelKind"]));
            }
            set {
                this["KPCAKernelKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2236")]
        public global::System.Nullable<System.Double> KPCASigma {
            get {
                return ((global::System.Nullable<System.Double>)(this["KPCASigma"]));
            }
            set {
                this["KPCASigma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public global::System.Nullable<System.Double> KPCAConstant {
            get {
                return ((global::System.Nullable<System.Double>)(this["KPCAConstant"]));
            }
            set {
                this["KPCAConstant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::System.Nullable<System.Int32> KPCADegree {
            get {
                return ((global::System.Nullable<System.Int32>)(this["KPCADegree"]));
            }
            set {
                this["KPCADegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::Accord.Statistics.Analysis.AnalysisMethod KPCAMethod {
            get {
                return ((global::Accord.Statistics.Analysis.AnalysisMethod)(this["KPCAMethod"]));
            }
            set {
                this["KPCAMethod"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\\\ComponentsAnalysis\\\\JoeWoodburyUtilities")]
        public string RecentProjectsRegistryKey {
            get {
                return ((string)(this["RecentProjectsRegistryKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecentProjects")]
        public string RecentProjectsDirName {
            get {
                return ((string)(this["RecentProjectsDirName"]));
            }
        }
    }
}
